// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyWccDp939fNVxM9G2SEq81Ko1prsfdKg',
    appId: '1:58762078793:web:0453984929cf4fb6c36d98',
    messagingSenderId: '58762078793',
    projectId: 'crud-84933',
    databaseURL: 'https://crud-84933-default-rtdb.firebaseio.com', // Corrected URL
    authDomain: 'crud-84933.firebaseapp.com',
    storageBucket: 'crud-84933.appspot.com',
    measurementId: 'G-QEF995R2SV',
  );


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqFgdcAJmP21biHK6msq3GmefGqkiZWis',
    appId: '1:58762078793:android:00252335f9703e46c36d98',
    messagingSenderId: '58762078793',
    projectId: 'crud-84933',
    storageBucket: 'crud-84933.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2tnALlHWacAEAKiw-I17FQx-NY0vqI84',
    appId: '1:58762078793:ios:a9f57859ab13399ec36d98',
    messagingSenderId: '58762078793',
    projectId: 'crud-84933',
    storageBucket: 'crud-84933.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2tnALlHWacAEAKiw-I17FQx-NY0vqI84',
    appId: '1:58762078793:ios:a9f57859ab13399ec36d98',
    messagingSenderId: '58762078793',
    projectId: 'crud-84933',
    storageBucket: 'crud-84933.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyWccDp939fNVxM9G2SEq81Ko1prsfdKg',
    appId: '1:58762078793:web:0b9c8c8341d1d592c36d98',
    messagingSenderId: '58762078793',
    projectId: 'crud-84933',
    authDomain: 'crud-84933.firebaseapp.com',
    storageBucket: 'crud-84933.appspot.com',
    measurementId: 'G-74DN5XBDSP',
  );
}
